# Support the author by using the funding link below
# Developed and mainted by Jon Cox.
# Buy Me a Coffee: https://buymeacoffee.com/joncox

buy_me_a_coffee: joncox123

# Your support helps me to continue the development of open source projects like this. Thanks, it means a lot!